# Site settings
title: Red Pitaya Notes
description: Notes on the Red Pitaya Open Source Instrument
baseurl: /red-pitaya-notes
url: http://pavel-demin.github.io

release-image: https://github.com/pavel-demin/red-pitaya-notes/releases/download/20180512/red-pitaya-alpine-3.6-armhf-20180512.zip

# Build settings
markdown: kramdown
highlighter: rouge
