# Site settings
title: Red Pitaya Notes
description: Notes on the Red Pitaya Open Source Instrument
baseurl: /red-pitaya-notes
url: http://pavel-demin.github.io

release-image: https://www.dropbox.com/sh/5fy49wae6xwxa8a/AAAn5aji7Tkcu2SGUlcmhkc9a/red-pitaya-alpine-3.6-armhf-20170919.zip?dl=1

# Build settings
markdown: kramdown
highlighter: rouge
